package parsers

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strings"

	"github.com/sonuKumar03/bundleradar/internal/core"
)

type AngularParser struct{}

var htmlAssetReference = regexp.MustCompile(`(?i)(?:src|href)\s*=\s*["']([^"']+)["']`)

func (p *AngularParser) Name() string {
	return "angular"
}

// Detect checks if the target was generated by Angular >= 17 (application builder / esbuild).
func (p *AngularParser) Detect(sample []byte, distDir string) bool {
	// Angular stats are esbuild metafiles; require the structural shape first
	// so a webpack/vite file that merely mentions Angular strings can't match.
	if !hasJSONKeys(sample, "inputs") {
		return false
	}

	// Direct Angular 17+ signatures
	if bytes.Contains(sample, []byte("@angular/")) ||
		bytes.Contains(sample, []byte("zone.js")) ||
		bytes.Contains(sample, []byte("angular:polyfills")) ||
		bytes.Contains(sample, []byte("angular:styles")) {
		return true
	}

	// Build output directory conventions specific to Angular application builder (browser/ folder)
	if distDir != "" {
		if fi, err := os.Stat(filepath.Join(distDir, "browser", "index.html")); err == nil && !fi.IsDir() {
			return true
		}
		cleanDist := filepath.ToSlash(distDir)
		if strings.HasSuffix(cleanDist, "/browser") {
			if fi, err := os.Stat(filepath.Join(distDir, "index.html")); err == nil && !fi.IsDir() {
				return true
			}
		}
	}

	return false
}

// Parse extracts bundle information from an Angular >= 17 application build metafile.
func (p *AngularParser) Parse(ctx context.Context, target core.Target) (*core.Bundle, error) {
	var meta EsbuildMetafile
	if err := decodeStats(ctx, target.StatsPath, &meta); err != nil {
		return nil, fmt.Errorf("parse angular stats JSON: %w", err)
	}

	if len(meta.Outputs) == 0 {
		return nil, fmt.Errorf("angular stats %q contains no outputs (expected Angular >= 17 esbuild metafile)", target.StatsPath)
	}

	distDir := resolveDistDir(target.StatsPath, target.DistPath)

	bundle := core.NewBundle(core.Metadata{
		Bundler: "angular",
	})

	initialFiles := make(map[string]bool)
	indexHTML, err := os.ReadFile(filepath.Join(distDir, "index.html"))
	if err == nil {
		for _, match := range htmlAssetReference.FindAllSubmatch(indexHTML, -1) {
			name := filepath.Base(strings.SplitN(string(match[1]), "?", 2)[0])
			if name != "." && name != string(filepath.Separator) {
				initialFiles[name] = true
			}
		}
	}

	// Iterate outputs in sorted key order so chunk/module ordering is
	// deterministic for identical metafiles (map iteration is randomized).
	sortedOutputs := make([]string, 0, len(meta.Outputs))
	for outPath := range meta.Outputs {
		sortedOutputs = append(sortedOutputs, outPath)
	}
	slices.Sort(sortedOutputs)

	// 1. Identify initial entrypoint roots:
	// In Angular 17+, roots are main JS, polyfills JS, and global styles CSS.
	initialRoots := make([]string, 0)
	isInitial := make(map[string]bool)

	for _, outPath := range sortedOutputs {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		out := meta.Outputs[outPath]
		ext := strings.ToLower(filepath.Ext(outPath))
		if ext == ".map" {
			bundle.AddAsset(core.Asset{
				Path:          outPath,
				SizeBytes:     out.Bytes,
				GzipBytes:     estimateGzip(out.Bytes, outPath),
				GzipEstimated: true,
				MimeType:      "application/json",
			})
			bundle.GzipEstimated = true
			continue
		}

		baseName := filepath.Base(outPath)
		lowerBase := strings.ToLower(baseName)
		lowerEntry := strings.ToLower(out.EntryPoint)

		isRoot := initialFiles[baseName] || initialFiles[outPath]
		if len(initialFiles) == 0 && (ext == ".js" || ext == ".mjs") && (strings.HasPrefix(lowerBase, "main") || strings.HasSuffix(lowerEntry, "main.ts")) {
			isRoot = true
		} else if len(initialFiles) == 0 && (ext == ".js" || ext == ".mjs") && (strings.HasPrefix(lowerBase, "polyfills") || strings.Contains(lowerEntry, "polyfills")) {
			isRoot = true
		} else if len(initialFiles) == 0 && ext == ".css" && (strings.HasPrefix(lowerBase, "styles") || strings.Contains(lowerEntry, "styles")) {
			isRoot = true
		}

		if isRoot {
			initialRoots = append(initialRoots, outPath)
			isInitial[outPath] = true
			isInitial[baseName] = true
		}
	}

	// 2. Traverse the static dependency graph using BFS along "import-statement" edges.
	// In modern Angular with esbuild, initial chunks statically import shared vendor/runtime chunks.
	// Dynamic route chunks are only referenced via "dynamic-import".
	queue := make([]string, len(initialRoots))
	copy(queue, initialRoots)

	for len(queue) > 0 {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		curr := queue[0]
		queue = queue[1:]

		out, ok := meta.Outputs[curr]
		if !ok {
			for k, v := range meta.Outputs {
				if filepath.Base(k) == curr {
					out = v
					ok = true
					break
				}
			}
		}
		if !ok {
			continue
		}

		for _, imp := range out.Imports {
			if imp.Kind == "import-statement" {
				impBase := filepath.Base(imp.Path)
				if !isInitial[impBase] {
					isInitial[impBase] = true
					isInitial[imp.Path] = true
					queue = append(queue, imp.Path)
				}
			}
		}
	}

	var initialBytes int64
	var initialGzipBytes int64
	var asyncBytes int64
	var initialChunkIDs []string

	// 2.5 Compute shortest import ingress path from entrypoint roots
	rootInputs := make([]string, 0)
	for _, outPath := range sortedOutputs {
		out := meta.Outputs[outPath]
		if !isInitial[outPath] && !isInitial[filepath.Base(outPath)] {
			continue
		}
		if out.EntryPoint != "" {
			rootInputs = append(rootInputs, out.EntryPoint)
		}
		for inPath := range out.Inputs {
			if strings.HasSuffix(inPath, "main.ts") || strings.HasSuffix(inPath, "main.js") ||
				strings.HasSuffix(inPath, "polyfills.ts") || strings.HasSuffix(inPath, "styles.css") {
				rootInputs = append(rootInputs, inPath)
			}
		}
	}
	if len(rootInputs) == 0 {
		for inPath := range meta.Inputs {
			if strings.HasSuffix(inPath, "main.ts") || strings.HasSuffix(inPath, "main.js") {
				rootInputs = append(rootInputs, inPath)
			}
		}
	}

	ingressPaths := make(map[string][]string)
	bfsQueue := make([]string, 0, len(rootInputs))
	for _, r := range rootInputs {
		if _, seen := ingressPaths[r]; !seen {
			ingressPaths[r] = []string{r}
			bfsQueue = append(bfsQueue, r)
		}
	}

	for len(bfsQueue) > 0 {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		curr := bfsQueue[0]
		bfsQueue = bfsQueue[1:]
		currPath := ingressPaths[curr]

		if inData, ok := meta.Inputs[curr]; ok {
			for _, imp := range inData.Imports {
				if imp.Kind != "import-statement" {
					continue
				}
				target := imp.Path
				if target == "" {
					continue
				}
				if _, seen := ingressPaths[target]; !seen {
					nextPath := make([]string, len(currPath)+1)
					copy(nextPath, currPath)
					nextPath[len(currPath)] = target
					ingressPaths[target] = nextPath
					bfsQueue = append(bfsQueue, target)
				}
			}
		}
	}

	seenModules := make(map[string]*core.Module)

	// 3. Process outputs: Separate code chunks from CSS and auxiliary assets
	for _, outPath := range sortedOutputs {
		out := meta.Outputs[outPath]
		ext := strings.ToLower(filepath.Ext(outPath))
		if ext == ".map" {
			continue
		}

		baseName := filepath.Base(outPath)

		// Non-JS assets (CSS, images, fonts, licenses)
		if ext != ".js" && ext != ".mjs" {
			gzBytes, estimated := gzipFor(distDir, outPath, out.Bytes)
			if ext == ".css" && (isInitial[outPath] || isInitial[baseName]) {
				// Global initial stylesheet
				initialBytes += out.Bytes
				initialGzipBytes += gzBytes
				initialChunkIDs = append(initialChunkIDs, baseName)
			}
			bundle.AddAsset(core.Asset{
				Path:          outPath,
				SizeBytes:     out.Bytes,
				GzipBytes:     gzBytes,
				GzipEstimated: estimated,
				MimeType:      inferMimeType(ext),
			})
			if estimated {
				bundle.GzipEstimated = true
			}
			continue
		}

		// JS Code Chunks
		gzBytes, estimated := gzipFor(distDir, outPath, out.Bytes)
		loadType := core.LoadTypeAsync
		if isInitial[outPath] || isInitial[baseName] {
			loadType = core.LoadTypeInitial
			initialChunkIDs = append(initialChunkIDs, baseName)
			initialBytes += out.Bytes
			initialGzipBytes += gzBytes
		} else {
			asyncBytes += out.Bytes
		}
		if estimated {
			bundle.GzipEstimated = true
		}

		chunk := core.Chunk{
			ID:            baseName,
			Name:          baseName,
			Path:          outPath,
			SizeBytes:     out.Bytes,
			GzipBytes:     gzBytes,
			GzipEstimated: estimated,
			Type:          loadType,
			Entry:         out.EntryPoint,
			ModuleIDs:     make([]string, 0, len(out.Inputs)),
		}

		// Process modules in chunk and deduplicate across chunks (sorted for determinism)
		inPaths := make([]string, 0, len(out.Inputs))
		for inPath := range out.Inputs {
			inPaths = append(inPaths, inPath)
		}
		slices.Sort(inPaths)
		for _, inPath := range inPaths {
			if err := ctx.Err(); err != nil {
				return nil, err
			}
			inBytes := out.Inputs[inPath]
			chunk.ModuleIDs = append(chunk.ModuleIDs, inPath)

			if existing, ok := seenModules[inPath]; ok {
				existing.ChunkIDs = append(existing.ChunkIDs, baseName)
				existing.ChunkBytes[baseName] = inBytes.BytesInOutput
				existing.SizeBytes += inBytes.BytesInOutput
				existing.GzipBytes += estimateGzip(inBytes.BytesInOutput, inPath)
			} else {
				pkgName := extractPackageName(inPath)
				isApp := (pkgName == "")
				var p []string
				if path, ok := ingressPaths[inPath]; ok {
					p = path
				}
				mod := &core.Module{
					ID:           inPath,
					Package:      pkgName,
					SizeBytes:    inBytes.BytesInOutput,
					GzipBytes:    estimateGzip(inBytes.BytesInOutput, inPath),
					IsAppCode:    isApp,
					ChunkIDs:     []string{baseName},
					ChunkBytes:   map[string]int64{baseName: inBytes.BytesInOutput},
					IngressPaths: p,
				}
				seenModules[inPath] = mod
			}
		}

		bundle.AddChunk(chunk)
	}

	// Add deduplicated modules to bundle in sorted ID order for determinism
	modIDs := make([]string, 0, len(seenModules))
	for id := range seenModules {
		modIDs = append(modIDs, id)
	}
	slices.Sort(modIDs)
	for _, id := range modIDs {
		bundle.AddModule(*seenModules[id])
	}

	// 4. Register primary application entrypoint
	entryName := "main"
	bundle.AddEntrypoint(entryName, core.Entrypoint{
		Name:             entryName,
		InitialBytes:     initialBytes,
		InitialGzipBytes: initialGzipBytes,
		AsyncBytes:       asyncBytes,
		ChunkIDs:         initialChunkIDs,
	})

	return bundle, nil
}

func inferMimeType(ext string) string {
	switch ext {
	case ".css":
		return "text/css"
	case ".html":
		return "text/html"
	case ".json":
		return "application/json"
	case ".map":
		return "application/json"
	default:
		return "application/octet-stream"
	}
}
